/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./index.html",
  ],
  theme: {
    extend: {
      colors: {
        // ── Exact palette from UI spec HTML files ──
        "primary":                   "#3b6546",
        "on-primary":                "#ffffff",
        "primary-container":         "#537e5d",
        "on-primary-container":      "#f6fff4",
        "primary-fixed":             "#bfeec6",
        "primary-fixed-dim":         "#a3d2ac",
        "on-primary-fixed":          "#00210d",
        "on-primary-fixed-variant":  "#254f32",
        "secondary":                 "#526254",
        "on-secondary":              "#ffffff",
        "secondary-container":       "#d2e5d3",
        "on-secondary-container":    "#566758",
        "secondary-fixed":           "#d5e7d5",
        "secondary-fixed-dim":       "#b9cbba",
        "on-secondary-fixed":        "#101f14",
        "on-secondary-fixed-variant":"#3b4b3d",
        "tertiary":                  "#824c56",
        "on-tertiary":               "#ffffff",
        "tertiary-container":        "#9e646e",
        "on-tertiary-container":     "#fffbff",
        "tertiary-fixed":            "#ffd9de",
        "tertiary-fixed-dim":        "#fab4bf",
        "on-tertiary-fixed":         "#350d17",
        "on-tertiary-fixed-variant": "#6a3841",
        "error":                     "#ba1a1a",
        "on-error":                  "#ffffff",
        "error-container":           "#ffdad6",
        "on-error-container":        "#93000a",
        "background":                "#f9f6ee",   // Bone white (day mode)
        "on-background":             "#1a1c19",
        "surface":                   "#f9f6ee",   // Bone white
        "on-surface":                "#1a1c19",
        "surface-variant":           "#e2e3de",
        "on-surface-variant":        "#414942",
        "surface-dim":               "#d9dad6",
        "surface-bright":            "#f9faf5",
        "surface-container-lowest":  "#fffdfa",
        "surface-container-low":     "#f4f1e6",
        "surface-container":         "#efede1",
        "surface-container-high":    "#e9e7db",
        "surface-container-highest": "#e4e2d6",
        "surface-tint":              "#3d6748",
        "outline":                   "#727971",
        "outline-variant":           "#c1c9bf",
        "inverse-surface":           "#2f312e",
        "inverse-on-surface":        "#f0f1ec",
        "inverse-primary":           "#a3d2ac",
      },
      fontFamily: {
        "headline": ["'Public Sans'", "sans-serif"],
        "body":     ["'Noto Serif'", "serif"],
        "label":    ["Manrope", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg":      "0.5rem",
        "xl":      "0.75rem",
        "full":    "9999px",
      },
    },
  },
  plugins: [],
}